"""initial migration

Revision ID: 8245a2e4febb
Revises: 
Create Date: 2026-04-13 14:51:57.578712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8245a2e4febb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'role',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('messages', 'sender',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('sessions', 'patient_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sessions', 'patient_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('messages', 'sender',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('messages', 'role',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
